### ISSUE TITLE
debug_toolbar could not be resolved

### ISSUE THREAD

**Issue by aayad72** [jazzband/django-debug-toolbar#1486]
Hi
I am new to python and django and running thru an issue with setting up the debug_toolbar getting a message bellow 

![image](https://user-images.githubusercontent.com/33642806/126535371-d05a7b35-d3a7-4745-9e20-8f4f8cb560a5.png)

here is the traceback

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/

Django Version: 3.2.5
Python Version: 3.9.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'playground',
 'debug_toolbar']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\base.py", line 233, in _get_session
    return self._session_cache

During handling of the above exception ('SessionStore' object has no attribute '_session_cache'), another exception occurred:
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 28, in model
    return self.get_model_class()
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 23, in get_model_class
    from django.contrib.sessions.models import Session
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\models.py", line 10, in <module>
    class Session(AbstractBaseSession):
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\db\models\base.py", line 113, in __new__
    raise RuntimeError(

During handling of the above exception (Model class django.contrib.sessions.models.Session doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.), another exception occurred:
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\debug_toolbar\middleware.py", line 67, in __call__
    panel.generate_stats(request, response)
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\debug_toolbar\panels\request.py", line 66, in generate_stats
    for k in sorted(request.session.keys())
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\base.py", line 169, in keys
    return self._session.keys()
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\base.py", line 238, in _get_session
    self._session_cache = self.load()
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 36, in _get_session_from_db
    except (self.model.DoesNotExist, SuspiciousOperation) as e:
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 28, in model
    return self.get_model_class()
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 23, in get_model_class
    from django.contrib.sessions.models import Session
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\models.py", line 10, in <module>
    class Session(AbstractBaseSession):
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\db\models\base.py", line 113, in __new__
    raise RuntimeError(

Exception Type: RuntimeError at /
Exception Value: Model class django.contrib.sessions.models.Session doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

is there any solution ???
I will appreciate any help

**Comment by tim-schilling** [comment]
Hi @aayad72,

The exception message is indicating that the `Session` model is not in the `INSTALLED_APPS`:

> Exception Value: Model class django.contrib.sessions.models.Session doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

Your `INSTALLED_APPS` setting does not include `django.contrib.sessions`, but your middleware has the session middleware:

```
MIDDLEWARE = [
...
'django.contrib.sessions.middleware.SessionMiddleware',
...]
```

Adding  `django.contrib.sessions` to your `INSTALLED_APPS` should resolve this error for you.


In regards to VSCode indicating the toolbar isn't installed, I suspect your virtualenv that you installed the toolbar into isn't the same as the one that VSCode is using. If you configure VSCode to use the same virtualenv, that warning should disappear.

**Comment by aayad72** [comment]
Even if I add django.contrib.session I still get RuntimeError, 
virtual env used screenshot
![image](https://user-images.githubusercontent.com/33642806/126566119-af8cfa46-7c5a-4063-b689-cd8819e6dafb.png)


Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/

Django Version: 3.2.5
Python Version: 3.9.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'playground',
 'debug_toolbar']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\base.py", line 233, in _get_session
    return self._session_cache

During handling of the above exception ('SessionStore' object has no attribute '_session_cache'), another exception occurred:
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 28, in model
    return self.get_model_class()
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 23, in get_model_class
    from django.contrib.sessions.models import Session
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\models.py", line 10, in <module>
    class Session(AbstractBaseSession):
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\db\models\base.py", line 113, in __new__
    raise RuntimeError(

During handling of the above exception (Model class django.contrib.sessions.models.Session doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.), another exception occurred:
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\debug_toolbar\middleware.py", line 67, in __call__
    panel.generate_stats(request, response)
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\debug_toolbar\panels\request.py", line 66, in generate_stats
    for k in sorted(request.session.keys())
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\base.py", line 169, in keys
    return self._session.keys()
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\base.py", line 238, in _get_session
    self._session_cache = self.load()
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 36, in _get_session_from_db
    except (self.model.DoesNotExist, SuspiciousOperation) as e:
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 28, in model
    return self.get_model_class()
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\backends\db.py", line 23, in get_model_class
    from django.contrib.sessions.models import Session
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\contrib\sessions\models.py", line 10, in <module>
    class Session(AbstractBaseSession):
  File "C:\Users\the_m\.virtualenvs\storefront-ynfQWea1\lib\site-packages\django\db\models\base.py", line 113, in __new__
    raise RuntimeError(

Exception Type: RuntimeError at /
Exception Value: Model class django.contrib.sessions.models.Session doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by tim-schilling** [comment]
Your error information and screenshot does not include `django.contrib.sessions` in your `INSTALLED_APPS`. You need to set:

```
INSTALLED_APPS = [
...
'django.contrib.sessions',
...
'debug_toolbar']
```

**Comment by aayad72** [comment]
I added 
INSTALLED_APPS = [
...
'django.contrib.sessions',
...
'debug_toolbar']

and i was still getting this error bellow
![image](https://user-images.githubusercontent.com/33642806/126571796-eb330da8-77dc-455e-a5ba-4a6f5ae6eeb5.png)

then I resolved the issue by running  
python manage.py migrate
python manage.py makemigrations

![image](https://user-images.githubusercontent.com/33642806/126571912-1ea681d5-de07-4a5c-9aee-ffe5a5c81d17.png)


Thanks for your help

**Comment by amanuelongithub** [comment]
`pip install django-debug-toolbar`
